### ISSUE TITLE
axiom-scan error: Tries to validate droplet name as IPv4 address

### ISSUE THREAD

**Issue by staz0t** [pry0cc/axiom#125]
First, it's an awesome tool. I love it.
I wanted to try distributed scanning, and axiom-scan is giving errors which says that it could not validate "dropletname" as an IPv4 address. Unfortunately, I could not debug the issue and fix it. Below is the output. Any help would be appreciated!

```
$ axiom-scan "test*" -iL=./resolved -p443 --banners -o=/tmp/masscantmp
Starting axiom-scan with module 'masscan' for fleet 'test*'
Splitting file ./resolved across all instances...
Running parallel file transfer...
=====================================================
Interlace v1.9.0	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
  0%|                                                                             | 0/3 [00:00<?, ?it/s][14:59:55] [THREAD] [rsync -e 'ssh -o StrictHostKeyChecking=no -F /home/stazot/.axiom/.sshconfig' -azr --progress /home/stazot/.axiom/tmp/6055c/test01.txt test01:input] Added to Queue 
[14:59:55] [THREAD] [rsync -e 'ssh -o StrictHostKeyChecking=no -F /home/stazot/.axiom/.sshconfig' -azr --progress /home/stazot/.axiom/tmp/6055c/test02.txt test02:input] Added to Queue 
[14:59:55] [THREAD] [rsync -e 'ssh -o StrictHostKeyChecking=no -F /home/stazot/.axiom/.sshconfig' -azr --progress /home/stazot/.axiom/tmp/6055c/test03.txt test03:input] Added to Queue 
sending incremental file list                                                                           
test02.txt

             42 100%    0.00kB/s    0:00:00  
             42 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/1)

100%|█████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.24it/s]Generated 3 commands in total
Repeat set to 1
sending incremental file list                                                                           
test01.txt

             32 100%    0.00kB/s    0:00:00  
             32 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/1)

sending incremental file list                                                                           
test03.txt

             42 100%    0.00kB/s    0:00:00  
             42 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/1)

100%|█████████████████████████████████████████████████████████████████████| 3/3 [00:08<00:00,  2.82s/it]
Launching masscan on fleet 'test*'...
=====================================================
Interlace v1.9.0	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 125, in str_to_int
    return _struct.unpack('>I', _inet_pton(AF_INET, addr))[0]
OSError: illegal IP address string passed to inet_pton

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 311, in __init__
    self._value = self._module.str_to_int(addr, flags)
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 129, in str_to_int
    raise AddrFormatError('%r is not a valid IPv4 address string!' % (addr,))
netaddr.core.AddrFormatError: 'test01' is not a valid IPv4 address string!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 791, in parse_ip_network
    ip = IPAddress(val1, module.version, flags=INET_PTON)
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 313, in __init__
    raise AddrFormatError('base address %r is not IPv%d'
netaddr.core.AddrFormatError: base address 'test01' is not IPv4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 265, in expand_partial_address
    tokens = ['%d' % int(addr)]
ValueError: invalid literal for int() with base 10: 'test01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 927, in __init__
    value, prefixlen = parse_ip_network(module, addr,
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 795, in parse_ip_network
    expanded_addr = _ipv4.expand_partial_address(val1)
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/strategy/ipv4.py", line 267, in expand_partial_address
    raise error
netaddr.core.AddrFormatError: invalid partial IPv4 address: 'test01'!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.0', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/interlace.py", line 36, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/threader.py", line 93, in __init__
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/core/input.py", line 249, in process_data_for_tasks_iterator
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/core/input.py", line 210, in _process_targets
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.0-py3.8.egg/Interlace/lib/core/input.py", line 207, in parse_and_group_target_specs
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/sets.py", line 121, in __init__
    for cidr in cidr_merge(mergeable):
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 1555, in cidr_merge
    cidr = IPNetwork(ip)
  File "/usr/local/lib/python3.8/dist-packages/netaddr-0.7.20-py3.8.egg/netaddr/ip/__init__.py", line 938, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % (addr,))
netaddr.core.AddrFormatError: invalid IPNetwork test01
Downloading output from fleet 'test*'...
Running parallel file transfer...
=====================================================
Interlace v1.9.0	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
=====================================================
  0%|                                                                             | 0/3 [00:00<?, ?it/s][15:00:07] [THREAD] [rsync -e 'ssh -o StrictHostKeyChecking=no -F /home/stazot/.axiom/.sshconfig' -azr --progress test01:output /home/stazot/.axiom/tmp/6055c/test01-out.txt] Added to Queue 
[15:00:07] [THREAD] [rsync -e 'ssh -o StrictHostKeyChecking=no -F /home/stazot/.axiom/.sshconfig' -azr --progress test02:output /home/stazot/.axiom/tmp/6055c/test02-out.txt] Added to Queue 
[15:00:07] [THREAD] [rsync -e 'ssh -o StrictHostKeyChecking=no -F /home/stazot/.axiom/.sshconfig' -azr --progress test03:output /home/stazot/.axiom/tmp/6055c/test03-out.txt] Added to Queue 
rsync: link_stat "/home/op/output" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1677) [Receiver=3.1.3]
rsync: [Receiver] write error: Broken pipe (32)
receiving incremental file list                                                                         

100%|█████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.59it/s]Generated 3 commands in total
Repeat set to 1
rsync: link_stat "/home/op/output" failed: No such file or directory (2)
rsync: link_stat "/home/op/output" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1677) [Receiver=3.1.3]
rsync: [Receiver] write error: Broken pipe (32)
receiving incremental file list                                                                         

100%|█████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  2.24it/s]rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1677) [Receiver=3.1.3]
rsync: [Receiver] write error: Broken pipe (32)
receiving incremental file list                                                                         

100%|█████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.58it/s]
Merging and sorting output...
cat: '/home/stazot/.axiom/tmp/6055c/test*-out.txt': No such file or directory
File saved to /tmp/masscantmp
```

**Comment by tume70** [comment]
I have the exact same issue on fresh install of Ubuntu 20.04 in digital ocean. I could guess this issue affects all new installations of axiom and all its interact modules.

**Comment by staz0t** [comment]
It probably has something to do with the use of doctl to fetch the IPs of the droplets. I guess axiom-scan is still under development.

**Comment by 0x540** [comment]
It is an issue in the latest Interlace update - target hostnames without a period break it - see:  https://github.com/codingo/Interlace/issues/123

**Comment by Isoterric** [comment]
^ this. The solution being put forward is pretty straight forward, so if you're feeling adventurous you could try doing the fix yourself. Just make the code change based on the [PR](https://github.com/codingo/Interlace/pull/124/files), reinstalled Interlace with `python3 setup.py install`. And you're good to go again!

**Comment by pry0cc** [comment]
Hey!

Also - just a word your syntax is off for the scan command. We have since changed since STÖK's video, the new syntax can be shown here https://github.com/pry0cc/axiom/wiki/Scans

Example:

`axiom-select 'fleet*'`
`axiom-scan input.txt --banners -p80,443 -o=output.txt`

**Comment by staz0t** [comment]
Hey @pry0cc, thanks for letting me know! I'll try that
