### ISSUE TITLE
Problem starting metasploit

### ISSUE THREAD

**Issue by kusayuzayushko** [pry0cc/axiom#210]
```localhost:~:% metasploit
Rails Error: Unable to access log file. Please ensure that /home/msf/.msf4/logs/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /home/msf/.msf4/logs/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Traceback (most recent call last):ork console...\
        16: from ./msfconsole:23:in `<main>'
        15: from /usr/src/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        14: from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        13: from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `driver'
        12: from /usr/src/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `new'
        11: from /usr/src/metasploit-framework/lib/msf/ui/console/driver.rb:74:in `initialize'
        10: from /usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:72:in `create'
         9: from /usr/src/metasploit-framework/lib/msf/base/simple/framework.rb:110:in `simplify'
         8: from /usr/src/metasploit-framework/lib/msf/base/config.rb:216:in `init'
         7: from /usr/src/metasploit-framework/lib/msf/base/config.rb:392:in `init'
         6: from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
         5: from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `each'
         4: from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
         3: from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
         2: from /usr/local/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
         1: from /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
/usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': No space left on device @ dir_s_mkdir - /home/msf/.msf4 (Errno::ENOSPC)
```

Is it just not enough space or something else?

**Comment by pry0cc** [comment]
Looking in to this..

**Comment by pry0cc** [comment]
So - it seems that the Linode nanode machines have TINY hard disks and so running metasploit actually fills the disk of the box. 

Try using a bigger instance, g6-standard-1 - put this into ~/.axiom/axiom.json under default_image and try a new instance and tell me if that worked!

**Comment by kusayuzayushko** [comment]
it wasn't nanonode, i was using g6-standart-1

**Comment by kusayuzayushko** [comment]
For some reason, axiom made nanode instead of standard. Is it my fault? Any idea what am i doing wrong?

![image](https://user-images.githubusercontent.com/521312/106908470-ea7c3880-6731-11eb-8fb7-14c550ba0a4e.png)

![image](https://user-images.githubusercontent.com/521312/106916488-d0deef00-6739-11eb-82ac-11f9e31ea33b.png)

**Comment by pry0cc** [comment]
That's super weird! Maybe rm it and try again?

**Comment by kusayuzayushko** [comment]
I've rebuilt everything, but no luck.

![image](https://user-images.githubusercontent.com/521312/106985917-e89b8f00-679c-11eb-949f-a8512e1085c1.png)
![image](https://user-images.githubusercontent.com/521312/106986022-17196a00-679d-11eb-910c-80945334fee9.png)

**Comment by Hebx** [comment]
Linode only gives you access to the image size that you requested for your instance storage at first . what you need to do is adding a disk of the unallocated storage from your axiom image and making it as a root (dev/sda) then reboot the linode instance .

**Comment by avistnm** [comment]
Use my code get it from here -
https://github.com/avistnm/Metasploit-avistnm.git
