### ISSUE TITLE
unable to run axiom-scan

### ISSUE THREAD

**Issue by pxng0lin** [pry0cc/axiom#214]
**I've tried to run axiom-scan with WSL ubuntu and just now my kali install, done this evening and im still getting the same error.

I tried with both dnsx and httpx

error:**

`kali@kali:~/a_pxngb0x/tools/Sudomy/output/02-05-2021/brexily.com$ axiom-scan httprobe_subdomain.txt -m httpx -o httpx-brexily.txt                                            
                                                                                                                     
Module: [ httpx  ] | Input: [ 42 targets ] | Instances: 10 [ kx01 kx02 kx03 kx04 kx05 kx06 kx07 kx08 kx09 kx10 ]
Command: [ cat input | /home/op/go/bin/httpx -o output  ] | Ext: [txt]
Cleaning up fleet... [ OK ]
Uploading input files to fleet...
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.2', 'console_scripts', 'interlace')())
  File "/usr/local/bin/interlace", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.2-py3.9.egg/Interlace/interlace.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.2-py3.9.egg/Interlace/lib/core/output.py", line 4, in <module>
ModuleNotFoundError: No module named 'colorclass'
Files uploaded...

Running jobs against specified targets... (To view logs: /home/kali/.axiom/tmp/httpx+1612572274)
tail: cannot open '/home/kali/.axiom/tmp/httpx+1612572274/logs/*' for reading: No such file or directory
tail: no files remaining
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.2', 'console_scripts', 'interlace')())
  File "/usr/local/bin/interlace", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.2-py3.9.egg/Interlace/interlace.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.2-py3.9.egg/Interlace/lib/core/output.py", line 4, in <module>
ModuleNotFoundError: No module named 'colorclass'
Scan complete...

Downloading output from fleet...
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.2', 'console_scripts', 'interlace')())
  File "/usr/local/bin/interlace", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.2-py3.9.egg/Interlace/interlace.py", line 6, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.2-py3.9.egg/Interlace/lib/core/output.py", line 4, in <module>
ModuleNotFoundError: No module named 'colorclass'
Files downloaded...
Mode set to txt.. Sorting unique.
cat: '/home/kali/.axiom/tmp/httpx+1612572274/output/*': No such file or directory
mv: cannot move '/home/kali/.axiom/tmp/httpx+1612572274/merge' to 'httpx-brexily.txt': Permission denied
Module [ httpx  ] | Time: [ 00h:00m:01s ] | Input: [ 42 targets ]
Output successfully saved to 'httpx-brexily.txt'! Logs are stored at '/home/kali/.axiom/logs/httpx+1612572274.tar.gz'`

**Not sure what's happening, the file has only domains not schema (http/https)**

**Comment by pry0cc** [comment]
ModuleNotFoundError: No module named 'colorclass' ? Do you need to install the dependencies first when installing interlace?

pip install -r requirements.txt inside the interlace folder?

**Comment by 0xtavian** [comment]
updated WSL setup (couldnt test) and tested with Kali, kali is working. If you can test and close the issue if its resolved that would be great. thank you!

**Comment by 0xtavian** [comment]
please reopen if this is not fixed.
