### ISSUE TITLE
naabu [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7bb614]

### ISSUE THREAD

**Issue by NitescuLucian** [pry0cc/axiom#512]
On:

```
axiom-scan dns.txt -m naabu -o ports.txt
```

Output:

```
goroutine 1 [running]:
github.com/projectdiscovery/mapcidr.AddressCountIpnet(0xc00009db30)
        /home/op/go/pkg/mod/github.com/projectdiscovery/mapcidr@v0.0.8/cidr.go:47 +0x14
github.com/projectdiscovery/ipranger.(*IPRanger).add(0xc0000326e0, {0xc00009db30, 0x23})
        /home/op/go/pkg/mod/github.com/projectdiscovery/ipranger@v0.0.3-0.20210831161617-ac80efae0961/ipranger.go:77 +0x67
github.com/projectdiscovery/ipranger.(*IPRanger).Add(0xc0000326e0, {0xc00009db30, 0x23})
        /home/op/go/pkg/mod/github.com/projectdiscovery/ipranger@v0.0.3-0.20210831161617-ac80efae0961/ipranger.go:65 +0x107
github.com/projectdiscovery/ipranger.(*IPRanger).AddHostWithMetadata(0xc0000326e0, {0xc00009db30, 0x23}, {0xa0e9ce, 0x0})
        /home/op/go/pkg/mod/github.com/projectdiscovery/ipranger@v0.0.3-0.20210831161617-ac80efae0961/ipranger.go:122 +0xc5
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).AddTarget(0xc00007d440, {0xc00009db30, 0xa1036d})
        /home/op/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.5/pkg/runner/targets.go:110 +0xdb
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).PreProcessTargets.func1(0xc000076000, 0xc000643c68, {0xc00009db30, 0xc0000bbc18})
        /home/op/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.5/pkg/runner/targets.go:90 +0x79
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).PreProcessTargets(0xc00007d440)
        /home/op/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.5/pkg/runner/targets.go:93 +0x1e5
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).Load(0xc00007d440)
        /home/op/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.5/pkg/runner/targets.go:29 +0x7a
github.com/projectdiscovery/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0xc00007d440)
        /home/op/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.5/pkg/runner/runner.go:118 +0x1fa
main.main()
        /home/op/go/pkg/mod/github.com/projectdiscovery/naabu/v2@v2.0.5/cmd/naabu/main.go:18 +0x15d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7bb614]
```

I tried reinstalling it, but with no effect.

**Comment by fail-open** [comment]
Working on my version I am running. What do you have in dns.txt? Guessing domain names?

**Comment by NitescuLucian** [comment]
@fail-open yes, domain names

**Comment by NitescuLucian** [comment]
I rebuilded today and seems to work just fine ... @fail-open did you find anything?
