### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 0xlittleboy** [pry0cc/axiom#574]
Hey, This error occured while subfinder 
``axiom-scan target.txt -m subfinder -pc ~/.config/subfinder/provider-config.yaml``
```
[13:18:26] [THREAD] [/home/op/go/bin/subfinder -silent -d target.com -o output/target.com -pc /home/op/.config/subfinder/provider-config.yaml] Added to Queue 
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.6', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.6-py3.8.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.6-py3.8.egg/Interlace/lib/core/input.py", line 381, in parse
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1870, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2401, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.6-py3.8.egg/Interlace/lib/core/input.py", line 427, in <lambda>
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.6-py3.8.egg/Interlace/lib/core/input.py", line 33, in check_positive
AttributeError: 'ArgumentParser' object has no attribute 'ArgumentTypeError'
```

**Comment by 0xtavian** [comment]
@0xlittleboy can you show me the entire output of the command including the banner etc?

**Comment by 0xtavian** [comment]
@0xlittleboy I fixed this issue. thanks. it shouldnt have caused any fatal error, its safe to ignore. thanks again for bringing it up. can you test again after running axiom-update and lmk if you still see that error?
