### ISSUE TITLE
Interlace Error

### ISSUE THREAD

**Issue by m3chboy** [pry0cc/axiom#639]
* When I run
`axiom-scan resolved.txt -m httpx -o output.txt`

* I'm getting this error
```
              _
  ____ __  __(_)___  ____ ___        ______________ _____
 / __ `/ |/_/ / __ \/ __ `__ \______/ ___/ ___/ __ `/ __ \
/ /_/ />  </ / /_/ / / / / / /_____(__  ) /__/ /_/ / / / /
\__,_/_/|_/_/\____/_/ /_/ /_/     /____/\___/\__,_/_/ /_/

                                    @pry0cc
                                 & @0xtavian

Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.6', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/lib/core/input.py", line 381, in parse
  File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1924, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.9/argparse.py", line 2455, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.9/argparse.py", line 2488, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/lib/core/input.py", line 427, in <lambda>
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/lib/core/input.py", line 33, in check_positiveAttributeError: 'ArgumentParser' object has no attribute 'ArgumentTypeError'
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.6', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/lib/core/input.py", line 381, in parse
  File "/usr/lib/python3.9/argparse.py", line 1830, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 1863, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.9/argparse.py", line 1924, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.9/argparse.py", line 2455, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.9/argparse.py", line 2488, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/lib/core/input.py", line 427, in <lambda>
  File "/usr/local/lib/python3.9/dist-packages/Interlace-1.9.6-py3.9.egg/Interlace/lib/core/input.py", line 33, in check_positiveAttributeError: 'ArgumentParser' object has no attribute 'ArgumentTypeError'
cat: /root/.axiom/tmp/httpx+16666731187790/hosts_preflight: No such file or directory
cp: cannot stat '/root/.axiom/tmp/httpx+16666731187790/hosts_preflight': No such file or directory
error with number of instances, exiting
```

**Comment by pdelteil** [comment]
Hi there,

What Python version are you using? Take a look at [this](https://github.com/pry0cc/axiom/issues/555#issuecomment-1133745166) thread.

**Comment by 0xtavian** [comment]
Can you show the stats prior to the scan running? Also, make sure you are on the latest code. @m3chboy

**Comment by 0xtavian** [comment]
@m3chboy 
Make sure you have instances selected with `axiom-select`
