### ISSUE TITLE
can't run axiom-exec id after fresh install

### ISSUE THREAD

**Issue by Nishantbhagat57** [pry0cc/axiom#659]
azureuser@linuxbbp:~$ axiom-exec id
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
cat: /home/azureuser/.axiom/tmp/exec/axiom-exec+1672775376/hosts_preflight: No such file or directory
cp: cannot stat '/home/azureuser/.axiom/tmp/exec/axiom-exec+1672775376/hosts_preflight': No such file or directory
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
tail: cannot open '/home/azureuser/.axiom/tmp/exec/axiom-exec+1672775376/logs/*' for reading: No such file or directory
tail: no files remaining
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace

![Screenshot 2023-01-04 012244](https://user-images.githubusercontent.com/64642374/210431111-5e15d9ca-c10b-461f-b791-c5a1c37dbaf1.png)

**Comment by pdelteil** [comment]
Hello,

This happens with you don't have any instance in `~/.axiom/selected.conf` 

Make sure your created instance is on the file. If not just run `axiom-select --auto`. 

I think this condition should be handled with an error/warning. What do you think @0xtavian?

**Comment by 0xtavian** [comment]
@pdelteil yea i agree we should add a check for number of instances selected. Not sure if this is issue is related but it very well could be. IIRC the instance should automatically be selected after running axiom-init/axiom-fleet but I’ll double check that as well. 

Also @Nishantbhagat57 I’m not sure how you got Azure to work. Last I checked I couldn’t get it working after updates to the azcli IIRC. Hopefully it works for you.

**Comment by Nishantbhagat57** [comment]
> `axiom-select --auto`

azureuser@linuxbbp:~$ axiom-select --auto
Selected: [ moser18 pasa15 ]
azureuser@linuxbbp:~$ axiom-exec whoami
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
cat: /home/azureuser/.axiom/tmp/exec/axiom-exec+1672835095/hosts_preflight: No such file or directory
cp: cannot stat '/home/azureuser/.axiom/tmp/exec/axiom-exec+1672835095/hosts_preflight': No such file or directory
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
tail: cannot open '/home/azureuser/.axiom/tmp/exec/axiom-exec+1672835095/logs/*' for reading: No such file or directory
tail: no files remaining
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
    return Distribution.from_name(distribution_name)
importlib.metadata.PackageNotFoundError: Interlace
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
azureuser@linuxbbp:~$ 

![Screenshot 2023-01-04 175607](https://user-images.githubusercontent.com/64642374/210554809-1c70593b-0613-4051-878c-63dc8fa20d33.png)

**Comment by Nishantbhagat57** [comment]
First I created an Ubuntu VM in Azure and using firefox I logged into Azure Portal.

Then used these steps from the Installation Manaul:

Clone the axiom repository
`git clone https://github.com/pry0cc/axiom ~/.axiom/`

Run configure script
`$HOME/.axiom/interact/axiom-configure`

Then it gives a link that I need to open in my browser...I copied in same firefox I am logged in with my azure acc. Sometimes it give error but after 2 3 tries it works. Then there was some Azure Vault error where I need to device login code. But after 2 3 tries it got resolved. And finally axiom can access my Azure account. But now it's this error :|

**Comment by 0xtavian** [comment]
@Nishantbhagat57 can you run `axiom-exec whoami —debug`, remove any sensitive info and upload to pastebin and share the link? Please and thank you.

**Comment by pdelteil** [comment]
I guess there's a problem with Interlace? 

What is your output if you run `pip show interlace` ?

**Comment by Nishantbhagat57** [comment]
> I guess there's a problem with Interlace?
> 
> What is your output if you run `pip show interlace` ?

So it was interlace problem

**Interlace was not installed. This is how I solved the problem:**
1. `git clone https://github.com/codingo/Interlace.git`
2. `cd Interlace`
3. `pip3 install -r requirements.txt`
4. `sudo su`
5. `cp -r /usr/lib/python3.8/site-packages/* /usr/local/lib/python3.8/dist-packages/`
6. Interlace is installed. Now I can use `interlace -h` to check the installation.

`axiom-exec id` is working now:

![Screenshot 2023-01-05 164529](https://user-images.githubusercontent.com/64642374/210767628-7f695525-858a-49a9-9f2b-09f0f937926b.png)

**Comment by 0xtavian** [comment]
Glad you got it working. I’m not sure how interlace didn’t get installed. It gets installed via axiom-configure btw. Going to close this issue. But feel free to comment if you have more issues.
