### ISSUE TITLE
MacOS bug - axiom-exec error unix_listener: path "XXXXXX" too long for Unix domain socket

### ISSUE THREAD

**Issue by gauravnarwani97** [pry0cc/axiom#663]
When running axiom-exec on Mac OS i get the following error:

unix_listener: path "/Users/asd/.axiom/tmp/exec/axiom-exec+1672937041/sockets/op@XXXXX-2266.UoExCMeWn60cfd9o" too long for Unix domain socket
unix_listener: path "/Users/asd/.axiom/tmp/exec/axiom-exec+1672937041/sockets/op@XXXX-2266.oc9ljxsb1QENUueT" too long for Unix domain socket
unix_listener: path "/Users/asd/.axiom/tmp/exec/axiom-exec+1672937041/sockets/op@XXXXX-2266.aF1QRFSN5gq7z4iS" too long for Unix domain socket
unix_listener: path "/Users/asd/.axiom/tmp/exec/axiom-exec+1672937041/sockets/op@XXXXX-2266.7skCqgtafPhoLB2d" too long for Unix domain socket
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/interlace.py", line 34, in main
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/lib/threader.py", line 112, in __init__
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/lib/core/input.py", line 263, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list
tail: cannot open '/Users/asd/.axiom/tmp/exec/axiom-exec+1672937041/logs/*' for reading: No such file or directory
tail: no files remaining
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/interlace.py", line 34, in main
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/lib/threader.py", line 112, in __init__
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/lib/core/input.py", line 263, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list
____________________________________
Interlace v1.9.7	by Michael Skelton (@codingo_)
                  	& Sajeeb Lohani (@sml555_)
____________________________________
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')())
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/interlace.py", line 34, in main
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/lib/threader.py", line 112, in __init__
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/interlace.py", line 11, in task_queue_generator_func
  File "/usr/local/lib/python3.10/site-packages/Interlace-1.9.7-py3.10.egg/Interlace/lib/core/input.py", line 263, in process_data_for_tasks_iterator
Exception: No target provided, or empty target list

**Comment by 0xtavian** [comment]
@gauravnarwani97 this is a super annoying bug in macOS. I’ve noticed the length of the pwd you execute in and the length of the axiom-scan command can cause this issue. I haven’t been able to fix it but till look into it again. Basically try to execute from a directory closer to /Users/asd. Can you show me the command you are running that causes this?

**Comment by gauravnarwani97** [comment]
Just basic `axiom-exec id`
I tried running the command from the home directory as well but still had the same result :(

**Comment by 0xtavian** [comment]
@gauravnarwani97 are you running the latest code (run `axiom-update` to be sure)? also what version of ssh are you running (`ssh -V`)? Maybe try updating ssh and trying again.

**Comment by 0xtavian** [comment]
@gauravnarwani97 your best bet might be installing the axiom control in an ubuntu docker images for now https://github.com/pry0cc/axiom#docker. Or spinning up an ubuntu 20.04 instance on the cloud provider and install the axiom controller on that. I’ll try to investigate more tonight.

**Comment by 0xtavian** [comment]
@gauravnarwani97 try this, since I cant recreate this issue atm, change this line https://github.com/pry0cc/axiom/blob/master/interact/axiom-exec#L63 from
`uid="axiom-exec+$(date +%s)"`
to 
`uid="$(date +%s)"`

**Comment by vysecurity** [comment]
issue still exists.
