### ISSUE TITLE
error after running axiom-scan 

### ISSUE THREAD

**Issue by sushantdhopat** [pry0cc/axiom#692]
/home/op/.axiom/interact/axiom-scan: line 712: generate_sshconfig: command not found
cat: /home/op/.axiom/selected.conf: No such file or directory
cp: cannot stat '/home/op/.axiom/.sshconfig': No such file or directory

**Comment by sushantdhopat** [comment]
also getting 

/home/op/.axiom/interact/axiom-scan: line 8: /home/op/.axiom/interact/includes/functions.sh: No such file or directory

**Comment by 0xtavian** [comment]
Make sure you run axiom-configure, which should run axiom-account-setup and then axiom-build. Once you have a valid image you can check with axiom-images ls. Finally you’ll need to spin up your fleet with axiom-init or axiom-fleet. 
the answers to these questions can be found in the FAQ section of the wiki. 
lmk if you run into any more issues.

**Comment by sushantdhopat** [comment]
i tried everything but not able to solve this errors 


/home/op/.axiom/interact/axiom-scan: line 712: generate_sshconfig: command not found
cat: /home/op/.axiom/selected.conf: No such file or directory
cp: cannot stat '/home/op/.axiom/.sshconfig': No such file or directory
Traceback (most recent call last):


 after running axiom-scan file -m httpx -o output

**Comment by 0xtavian** [comment]
@sushantdhopat show me the output of `axiom-ls` please

**Comment by sushantdhopat** [comment]
![Screenshot 2023-03-02 at 5 05 13 AM](https://user-images.githubusercontent.com/57283755/222291257-3df9d991-dd3d-4460-a06b-37a0ae397f41.png)

**Comment by 0xtavian** [comment]
That’s axiom-scan not axiom-ls

**Comment by sushantdhopat** [comment]
sorry didn't see yet here is it 
![Screenshot 2023-03-02 at 5 08 13 AM](https://user-images.githubusercontent.com/57283755/222291812-2082fddd-fe9f-4cf8-b7e8-607e87eb7379.png)

**Comment by 0xtavian** [comment]
You have to run `axiom-account-setup`. Then axiom-build. Then axiom-fleet and then you can scan. Please read the wiki. Not sure how you missed this part. 

You might as well just run 
`bash <(curl -s https://raw.githubusercontent.com/pry0cc/axiom/master/interact/axiom-configure)` all over again.

**Comment by sushantdhopat** [comment]
no, I done this all properly

**Comment by 0xtavian** [comment]
Please do it again. You don’t have an account setup. What Os are you running? Make sure you updated all packages beforehand with `sudo apt dust-upgrade`

**Comment by sushantdhopat** [comment]
i am using digital ocean os Ubuntu 22.10 x64 yaa i will try it again

**Comment by sushantdhopat** [comment]
can u troubleshoot this below error i am not getting output of axiom scan i done lot time with above bash nothing happen anything i just lossing dollar to create the snapshot 

here is error

```
/home/op/.axiom/interact/axiom-scan: line 712: generate_sshconfig: command not found
cat: /home/op/.axiom/selected.conf: No such file or directory
cp: cannot stat '/home/op/.axiom/.sshconfig': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/lib/core/input.py", line 381, in parse
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1870, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2401, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/lib/core/input.py", line 427, in <lambda>
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/lib/core/input.py", line 33, in check_positive
AttributeError: 'ArgumentParser' object has no attribute 'ArgumentTypeError'
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.7', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/lib/core/input.py", line 381, in parse
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1870, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2401, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/lib/core/input.py", line 427, in <lambda>
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.7-py3.8.egg/Interlace/lib/core/input.py", line 33, in check_positive
AttributeError: 'ArgumentParser' object has no attribute 'ArgumentTypeError'
cat: /home/op/.axiom/tmp/httpx+167804139926241/hosts_preflight: No such file or directory
cp: cannot stat '/home/op/.axiom/tmp/httpx+167804139926241/hosts_preflight': No such file or directory

```

**Comment by 0xtavian** [comment]
@sushantdhopat sorry you are still having trouble. I’ll try tonight with a fresh ubuntu 22.10 instance. Can you try installing axiom one last time but this time with a fresh ubuntu 20.04 instance? 

This errors is likely due to not having any axiom instances spun up or selected. 

can you show me the output of `axiom-selected` `axiom-ls`, `axiom-account` and `axiom-images ls`?
There might have been previous errors showing the issue that could be easy to miss. 

If you can try again with a fresh Ubuntu 20.04 instance that would be very much appreciated. I’ll try to make time in a couple of hours to test with 22.10. 

You should be able to delete snapshots with `axiom-images rm`
