### ISSUE TITLE
Interlace Error on axiom first scan

### ISSUE THREAD

**Issue by bughunter0xff** [pry0cc/axiom#788]
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
Traceback (most recent call last):
  File "/usr/bin/interlace", line 33, in <module>
    sys.exit(load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')())
  File "/usr/bin/interlace", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: Interlace
cat: /home/ubuntu/.axiom/tmp/amass+170941708624275/hosts_preflight: No such file or directory
cp: cannot stat '/home/ubuntu/.axiom/tmp/amass+170941708624275/hosts_preflight': No such file or directory

**Comment by xqd-ai** [comment]
I'm also getting this error on linode fresh install, any solution?!
