### ISSUE TITLE
Multiple errors in axiom-scan at first run after installation

### ISSUE THREAD

**Issue by tthtlc** [pry0cc/axiom#821]
I just completed my axiom installation.   Then I did a axiom-fleet, and then axiom-ssh to connect in.   then I generated a file using chaos (and my chaos key) and output to XXXX.

Then following that:

axiom-scan XXXX -m dnsx -w /tmp/ooo

/home/op/.axiom/interact/axiom-scan: line 8: /home/op/.axiom/interact/includes/functions.sh: No such file or directory
              _
  ____ __  __(_)___  ____ ___        ______________ _____
 / __ `/ |/_/ / __ \/ __ `__ \______/ ___/ ___/ __ `/ __ \
/ /_/ />  </ / /_/ / / / / / /_____(__  ) /__/ /_/ / / / /
\__,_/_/|_/_/\____/_/ /_/ /_/     /____/\___/\__,_/_/ /_/

                                    @pry0cc
                                 & @0xtavian

/home/op/.axiom/interact/axiom-scan: line 747: generate_sshconfig: command not found
cat: /home/op/.axiom/selected.conf: No such file or directory
cp: cannot stat '/home/op/.axiom/.sshconfig': No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 389, in parse
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1870, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2401, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 435, in <lambda>
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 31, in check_positive
AttributeError: 'ArgumentParser' object has no attribute 'ArgumentTypeError'
Traceback (most recent call last):
  File "/usr/local/bin/interlace", line 11, in <module>
    load_entry_point('Interlace==1.9.8', 'console_scripts', 'interlace')()
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/interlace.py", line 24, in main
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 389, in parse
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1870, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2401, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 435, in <lambda>
  File "/usr/local/lib/python3.8/dist-packages/Interlace-1.9.8-py3.8.egg/Interlace/lib/core/input.py", line 31, in check_positive
AttributeError: 'ArgumentParser' object has no attribute 'ArgumentTypeError'
cat: /home/op/.axiom/tmp/dnsx+173206802232643/hosts_preflight: No such file or directory
cp: cannot stat '/home/op/.axiom/tmp/dnsx+173206802232643/hosts_preflight': No such file or directory
error with number of instances, exiting
229:~:%

**Comment by tthtlc** [comment]
thank you for the support.
